# 插件使用的语言文件
language: zh_cn

# 允许将 Vault 货币作为资产添加，并可从你的账户中提取或存入
vault-support: true

# 允许将 PlayerPoints 货币作为资产添加，并可从你的账户中提取或存入
player-points-support: true

colors: # 允许自定义命令输出和图表的颜色
  # 价格上涨时使用的颜色（十六进制）
  bullish: "#8CD740"

  # 价格下跌时使用的颜色（十六进制）
  bearish: "#FA413B"

database:
  # 如果为 false，则订单可以跨世界交易
  data-per-world: false

  # (0)-SQLite (1)-MySQL
  database-type: 0

  mysql:
    host:
    port:
    database:
    username:
    password:
    options: "?useSSL=true&requireSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true"

exchange:
  fees: # 固定费用: 23    百分比费用: 23%
    # 从钱包取钱时收取的费用
    withdrawal-fees: 0
    # 向钱包存钱时收取的费用
    deposit-fees: 0

  commodities:
    fees: # 固定费用: 23    百分比费用: 23%
      # 与其他订单立即成交时收取的费用
      taker-fees: 0
      # 向订单簿中添加订单时收取的费用
      maker-fees: 0

      # 使用实体认领标签时收取的费用（仅限固定费用）
      entity-claiming-fees: 0

    # 当进行交易时，大宗商品会在账户的交付位置生成实体物品（若为 false 则直接将大宗商品添加到钱包）
    physical-delivery: false

    # 允许从钱包中提取大宗商品用于交易
    take-wallet: true

    # 允许从背包中提取物品用于交易
    take-inventory: true

    # 允许从世界中提取已认领的实体用于交易
    take-world: true

    # 说明：大宗商品是以散装形式交易的原材料且可互换的物品，通常会被加工为其他产品
    #       作物和建筑材料也可以是大宗商品：
    #
    #       IRON 在现实生活中是大宗商品
    #             - 所有铁锭质量相同，因此可以互换（可替代/Fungible） v
    #             - 以大批量交易（散装交易/Traded in Bulk） v
    #             - 通常从地里开采（原材料/Raw material） v
    #
    #       DIAMOND HELMET（钻石头盔）不是大宗商品
    #             - 附魔、耐久和装饰会让每一个都独一无二（不可替代/Non-Fungible） x
    #             - 通常一次只交易一个（非散装） x
    #             - 成品（非原材料） x
    #
    #     不过这仅仅是建议，你可以按照自己的想法来使用这个插件。
    #
    generation:
      # 通过白名单/黑名单，在每个世界中为大宗商品自动生成资产
      active: true

      # 启用白名单并禁用物品黑名单
      item-whitelisting: true
      commodity-item-whitelist:
        - COAL
        - CHARCOAL
        - IRON_INGOT
        - COPPER_INGOT
        - GOLD_INGOT
        - NETHERITE_SCRAP
        - AMETHYST_SHARD
        - DIAMOND
        - NETHER_QUARTZ
        - EMERALD
        - LAPIS_LAZULI
        - GLOWSTONE_DUST
        - REDSTONE
        - WHEAT
        - EGG
        - APPLE
        - MELON_SLICE
        - PUMPKIN
        - SWEET_BERRIES
        - GLOW_BERRIES
        - CHORUS_FRUIT
        - CARROT
        - POTATO
        - POISONOUS_POTATO
        - BEETROOT
        - FISH
        - RAW_COD
        - RAW_SALMON
        - TROPICAL_FISH
        - PUFFERFISH
        - SUGARCANE
        - KELP
        - COCOA_BEANS
        - HONEY_BOTTLE
        - SPIDER_EYE
        - ROTTEN_FLESH
        - FLINT
        - BONE
        - STRING
        - FEATHER
        - LEATHER
        - HONEYCOMB
        - INK_SAC
        - GLOW_INK_SAC
        - TURTLE_SCUTE
        - ARMADILLO_SCUTE
        - SLIME_BALL
        - CLAY_BALL
        - PRISMARINE_SHARD
        - PRISMARINE_CRYSTALS
        - NAUTILUS_SHELL
        - HEART_OF_THE_SEA
        - BLAZE_ROD
        - BREEZE_ROD
        - HEAVY_CORE
        - NETHER_STAR
        - ENDER_PEARL
        - SHULKER_SHELL
        - ECHO_SHARD
        - NETHER_WART
        - GUNPOWDER
        - DRAGON_BREATH
        - GHAST_TEAR
        - PHANTOM_MEMBRANE
        - BAMBOO
        - CACTUS
        - POWDER_SNOW_BUCKET
        - INK_SAC
        - WATER_BUCKET
        - MILK_BUCKET
        - LAVA_BUCKET
        - OAK_LOG
        - SPRUCE_LOG
        - BIRCH_LOG
        - JUNGLE_LOG
        - ACACIA_LOG
        - DARK_OAK_LOG
        - MANGROVE_LOG
        - CHERRY_LOG
        - CRIMSON_STEM
        - WARPED_STEM
        - DIRT
        - GRAVEL
        - SAND
        - COBBLESTONE
        - GRANITE
        - DIORITE
        - ANDESITE
        - OBSIDIAN
        - NETHERRACK
        - SPONGE
        - SOUL_SAND
        - SOUL_SOIL
        - ICE
        - END_STONE
        - TOTEM_OF_UNDYING
        - BROWN_MUSHROOM
        - RED_MUSHROOM

      commodity-item-blacklist:
        - BARRIER
        - COMMAND_BLOCK
        - STRUCTURE_BLOCK
        - STRUCTURE_VOID

      # 启用实体白名单并禁用黑名单
      entity-whitelisting: true
      commodity-entity-whitelist:
        - PIG
        - SHEEP
        - COW
        - CHICKEN
        - MOOSHROOM
        - VILLAGER

      # 凋灵可以被用来挖矿……想象一下拿凋灵来交易……嗯……
      commodity-entity-blacklist:
        - ENDER_DRAGON
        - WARDEN

  forex:
    fees: # 固定费用: 23    百分比费用: 23%
      # 与其他订单立即成交时收取的费用
      taker-fees: 0
      # 向订单簿中添加订单时收取的费用
      maker-fees: 0

main-currency: # 交易所中用于交易的主要货币设置（可以在游戏内更改）

  # 将主要货币设置为代码匹配的现有货币
  # 如果没有找到匹配项，将使用下面的参数创建此资产
  currency: EMD_Villager Emerald_#00ff00
  #
  #           <code>_<name>_<hex color>
  #
  # 示例: EMD_Villager Emerald_#21ff59   （如果你希望即使未找到也能显示得好看，推荐使用这个例子）
  # 示例: USD_US dollars                 （如果你希望使用随机颜色）
  # 示例: EUR                            （如果你非常确定该货币已经存在）
  #
  # 创建说明：
  # 只能使用 3 位字母代码，例如: USD ---> 你有: 89.32 USD !!
  # 名称、颜色和描述都是可选的。（颜色会随机选择）（名称默认使用代码）

  # 新玩家在钱包中默认拥有的主要货币数量（使用非 0 数值可能会导致货币贬值，仅在你想设置初始供应时使用）
  initial-balance: 0