# 插件使用的语言文件
language: zh_cn

# 允许将 Vault 货币作为资产添加，并可从你的账户中提取或存入
vault-support: true

# 允许将 PlayerPoints 货币作为资产添加，并可从你的账户中提取或存入
player-points-support: true

colors: # 允许自定义命令输出和图表的颜色
  # 价格上涨时使用的颜色（十六进制）
  bullish: "#8CD740"

  # 价格下跌时使用的颜色（十六进制）
  bearish: "#FA413B"

database:
  # note: per-world data feature removed; plugin always uses server-wide shared data
  data-per-world: false

  # (0)-SQLite (1)-MySQL
  database-type: 0

  mysql:
    host:
    port:
    database:
    username:
    password:
    options: "?useSSL=true&requireSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true"

exchange:
  fees: # 固定费用: 23    百分比费用: 23%
    # 从钱包取钱时收取的费用
    withdrawal-fees: 0
    # 向钱包存钱时收取的费用
    deposit-fees: 0

  commodities:
    fees: # 固定费用: 23    百分比费用: 23%
      # 与其他订单立即成交时收取的费用
      taker-fees: 0
      # 向订单簿中添加订单时收取的费用
      maker-fees: 0

      # 使用实体认领标签时收取的费用（仅限固定费用）
      entity-claiming-fees: 0

    # 当进行交易时，大宗商品会在账户的交付位置生成实体物品（若为 false 则直接将大宗商品添加到钱包）
    physical-delivery: false

    # 允许从钱包中提取大宗商品用于交易
    take-wallet: true

    # 允许从背包中提取物品用于交易
    take-inventory: true

    # 允许从世界中提取已认领的实体用于交易
    take-world: true

    # 说明：大宗商品是以散装形式交易的原材料且可互换的物品，通常会被加工为其他产品
    #       作物和建筑材料也可以是大宗商品：
    #
    #       IRON 在现实生活中是大宗商品
    #             - 所有铁锭质量相同，因此可以互换（可替代/Fungible） v
    #             - 以大批量交易（散装交易/Traded in Bulk） v
    #             - 通常从地里开采（原材料/Raw material） v
    #
    #       DIAMOND HELMET（钻石头盔）不是大宗商品
    #             - 附魔、耐久和装饰会让每一个都独一无二（不可替代/Non-Fungible） x
    #             - 通常一次只交易一个（非散装） x
    #             - 成品（非原材料） x
    #
    #     不过这仅仅是建议，你可以按照自己的想法来使用这个插件。
    #
    generation:
      # 通过白名单/黑名单，在每个世界中为大宗商品自动生成资产
      active: true

      # 启用白名单并禁用物品黑名单
      item-whitelisting: true
      commodity-item-whitelist:
        - minecraft:COAL
        - minecraft:CHARCOAL
        - minecraft:IRON_INGOT
        - minecraft:COPPER_INGOT
        - minecraft:GOLD_INGOT
        - minecraft:NETHERITE_SCRAP
        - minecraft:AMETHYST_SHARD
        - minecraft:DIAMOND
        - minecraft:NETHER_QUARTZ
        - minecraft:EMERALD
        - minecraft:LAPIS_LAZULI
        - minecraft:GLOWSTONE_DUST
        - minecraft:REDSTONE
        - minecraft:WHEAT
        - minecraft:EGG
        - minecraft:APPLE
        - minecraft:MELON_SLICE
        - minecraft:PUMPKIN
        - minecraft:SWEET_BERRIES
        - minecraft:GLOW_BERRIES
        - minecraft:CHORUS_FRUIT
        - minecraft:CARROT
        - minecraft:POTATO
        - minecraft:POISONOUS_POTATO
        - minecraft:BEETROOT
        - minecraft:FISH
        - minecraft:RAW_COD
        - minecraft:RAW_SALMON
        - minecraft:TROPICAL_FISH
        - minecraft:PUFFERFISH
        - minecraft:SUGARCANE
        - minecraft:KELP
        - minecraft:COCOA_BEANS
        - minecraft:HONEY_BOTTLE
        - minecraft:SPIDER_EYE
        - minecraft:ROTTEN_FLESH
        - minecraft:FLINT
        - minecraft:BONE
        - minecraft:STRING
        - minecraft:FEATHER
        - minecraft:LEATHER
        - minecraft:HONEYCOMB
        - minecraft:INK_SAC
        - minecraft:GLOW_INK_SAC
        - minecraft:TURTLE_SCUTE
        - minecraft:ARMADILLO_SCUTE
        - minecraft:SLIME_BALL
        - minecraft:CLAY_BALL
        - minecraft:PRISMARINE_SHARD
        - minecraft:PRISMARINE_CRYSTALS
        - minecraft:NAUTILUS_SHELL
        - minecraft:HEART_OF_THE_SEA
        - minecraft:BLAZE_ROD
        - minecraft:BREEZE_ROD
        - minecraft:HEAVY_CORE
        - minecraft:NETHER_STAR
        - minecraft:ENDER_PEARL
        - minecraft:SHULKER_SHELL
        - minecraft:ECHO_SHARD
        - minecraft:NETHER_WART
        - minecraft:GUNPOWDER
        - minecraft:DRAGON_BREATH
        - minecraft:GHAST_TEAR
        - minecraft:PHANTOM_MEMBRANE
        - minecraft:BAMBOO
        - minecraft:CACTUS
        - minecraft:POWDER_SNOW_BUCKET
        - minecraft:INK_SAC
        - minecraft:WATER_BUCKET
        - minecraft:MILK_BUCKET
        - minecraft:LAVA_BUCKET
        - minecraft:OAK_LOG
        - minecraft:SPRUCE_LOG
        - minecraft:BIRCH_LOG
        - minecraft:JUNGLE_LOG
        - minecraft:ACACIA_LOG
        - minecraft:DARK_OAK_LOG
        - minecraft:MANGROVE_LOG
        - minecraft:CHERRY_LOG
        - minecraft:CRIMSON_STEM
        - minecraft:WARPED_STEM
        - minecraft:DIRT
        - minecraft:GRAVEL
        - minecraft:SAND
        - minecraft:COBBLESTONE
        - minecraft:GRANITE
        - minecraft:DIORITE
        - minecraft:ANDESITE
        - minecraft:OBSIDIAN
        - minecraft:NETHERRACK
        - minecraft:SPONGE
        - minecraft:SOUL_SAND
        - minecraft:SOUL_SOIL
        - minecraft:ICE
        - minecraft:END_STONE
        - minecraft:TOTEM_OF_UNDYING
        - minecraft:BROWN_MUSHROOM
        - minecraft:RED_MUSHROOM

      commodity-item-blacklist:
        - BARRIER
        - COMMAND_BLOCK
        - STRUCTURE_BLOCK
        - STRUCTURE_VOID

      # 启用实体白名单并禁用黑名单
      entity-whitelisting: true
      commodity-entity-whitelist: []

      # 凋灵可以被用来挖矿……想象一下拿凋灵来交易……嗯……
      commodity-entity-blacklist:
        - ENDER_DRAGON
        - WARDEN

  forex:
    fees: # 固定费用: 23    百分比费用: 23%
      # 与其他订单立即成交时收取的费用
      taker-fees: 0
      # 向订单簿中添加订单时收取的费用
      maker-fees: 0

main-currency: # 交易所中用于交易的主要货币设置（可以在游戏内更改）

  # 将主要货币设置为代码匹配的现有货币
  # 如果没有找到匹配项，将使用下面的参数创建此资产
  currency: EMD_Villager Emerald_#00ff00
  #
  #           <code>_<name>_<hex color>
  #
  # 示例: EMD_Villager Emerald_#21ff59   （如果你希望即使未找到也能显示得好看，推荐使用这个例子）
  # 示例: USD_US dollars                 （如果你希望使用随机颜色）
  # 示例: EUR                            （如果你非常确定该货币已经存在）
  #
  # 创建说明：
  # 只能使用 3 位字母代码，例如: USD ---> 你有: 89.32 USD !!
  # 名称、颜色和描述都是可选的。（颜色会随机选择）（名称默认使用代码）

  # 新玩家在钱包中默认拥有的主要货币数量（使用非 0 数值可能会导致货币贬值，仅在你想设置初始供应时使用）
  initial-balance: 0